version: "3.8"
services:
  redis:
    container_name: hydro-guardian-redis
    image: redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - '6379:6379'
    volumes:
      - redis:/data
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net

volumes:
  redis:
    driver: local

networks:
  rabbitmq_go_net:
    driver: bridge
