version: 2.1

jobs:
  lint-backend:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
            name: "Lint Backend"
            command: |
              echo "[CODE QUALITY] Linting Backend Module"
              cd backend/
              npm i
              npm run lint

workflows:
  code-quality:
    jobs:
      - lint-backend
