import { IsEmail, IsString, Matches, MinLength } from 'class-validator';
import { ValidationMessages } from '../enums/validation-messages.enum';
import { ApiProperty } from '@nestjs/swagger';

export class SignUpDto {
  @ApiProperty({
    example: 'john.doe@example.com',
    description:
      'Email linked to this account. This value should be equal to the one, that was provided on invitation creation step.',
    required: true,
  })
  @IsEmail({}, { message: ValidationMessages.MUST_BE_EMAIL })
  email: string;

  @ApiProperty({
    example: 'Abc123!Abc',
    description:
      'Password that should match default AWS Cognito Policy. https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-policies.html',
    required: true,
  })
  @IsString({ message: ValidationMessages.MUST_BE_STRING })
  @MinLength(8, { message: ValidationMessages.MIN_LENGTH_IS + 8 })
  @Matches(
    /^(?=.*\d)(?=.*[!@#$%^&*()-_=+[\]{};:'",.<>/\\?|])(?=.*[A-Z])(?=.*[a-z]).*$/,
    { message: ValidationMessages.MUST_BE_VALID_PASSWORD },
  )
  password: string;

  @ApiProperty({
    example: 'John',
    description: 'First name linked to this account.',
  })
  @IsString({ message: ValidationMessages.MUST_BE_STRING })
  firstName: string;

  @ApiProperty({
    example: 'Doe',
    description: 'Last name linked to this account.',
  })
  @IsString({ message: ValidationMessages.MUST_BE_STRING })
  lastName: string;

  @ApiProperty({
    example: '635417',
    description: 'Invitation code that was generated by admin.',
  })
  @Matches(/^[A-Za-z0-9!@#$%^&*()_=+[\]{};:',.<>/\\?|]*$/, {
    message: ValidationMessages.MUST_BE_VALID_INVITATION_CODE_FORMAT,
  })
  invitationCode: string;
}
